### ISSUE TITLE
ThorVG 0.13 Release

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2067]
### Tasks Review
- [x] https://github.com/thorvg/thorvg/issues/2138
- [x] https://github.com/thorvg/thorvg/issues/2116
- [x] https://github.com/thorvg/thorvg/pull/2143
- [x] https://github.com/thorvg/thorvg/issues/2129
- [x] https://github.com/thorvg/thorvg/issues/2047
- [x] https://github.com/thorvg/thorvg/issues/1931
- [x] https://github.com/thorvg/thorvg/issues/2061
- [x] https://github.com/thorvg/thorvg/issues/2093
- [x] https://github.com/thorvg/thorvg/issues/1487
- [x] https://github.com/thorvg/thorvg/issues/2083
- [x] https://github.com/thorvg/thorvg/pull/2077
- [x] https://github.com/thorvg/thorvg/pull/2057
- [x] https://github.com/thorvg/thorvg/issues/2058
- [x] https://github.com/thorvg/thorvg/issues/1912
- [x] https://github.com/thorvg/thorvg/issues/2070

### API Clean UP
- [x] https://github.com/thorvg/thorvg/pull/2091

### Unit Test
- [x] Make it up 80% coverage https://github.com/thorvg/thorvg/wiki/Unit-Tests

### Regression Test
- [x] TVG binary compatibility
- [x] Unit-Tests
- [x] Examples
- [x] Memory Sanitizer (Examples / Unit-Tests)  //-Db_sanitize="address,undefined"
- [x] Thread Sanitizer (Examples / Unit-Tests)    //-Db_sanitize="thread"
- [x] Tools (svg2png / svg2tvg / lottie2gif)
- [x] GL Engine capability https://github.com/thorvg/thorvg/issues/1687
- [x] WG Engine capability https://github.com/thorvg/thorvg/issues/1479

### Update the TVG Pictures
- [x] Update the TVG Pictures in [examples, test] with the latest SVG resources
- [x] Back up the new generated tvg picture binaries to https://github.com/thorvg/tvgpack

### Performance Comparison
- [x] Stress Test (at the sampling 1000, within the margin of error)
> - Performance = **1.01x faster** (0.0134s -> 0.0133s)
> - Lottie = **1.38x faster** (0.0287s -> 0.0208s)
- [x] Binary size diff (**full feature set:** loaders="all", savers="all", bindings="capi")
> - Base: Sw Raster with the vector drawing primitives = **+10kb** (129kb -> 139kb)
> - Base + SVG loader only = **+8kb** (196kb -> 205kb)
> - Base + Lottie loader with static (lottie, png, jpg, webp) = **+90kb** (262kb -> 352kb)  //static webp introduced
> - Base + Full set with external = **+38kb** (294kb -> 332kb) //ttf introduced
> - Base + Full set with static = **+98kb** (357kb -> 455kb)  //static webp & ttf introduced

### Build Test
- [x] Build errors / warnings (Web/Ubuntu/Windows/MacOS)

### Update API Documentation
- [x] Update the api documenation with doxygen 

### Update the thorvg package
- [x] ThorVG Lottie Player https://www.npmjs.com/package/@thorvg/lottie-player
- [x] ThorVG Viewer https://github.com/thorvg/thorvg.viewer
- [x] ThorVG Test Automation https://github.com/thorvg/thorvg.test-automation
- [x]  ThorVG Android https://github.com/thorvg/thorvg.android
- [x]  MSYS2 https://github.com/thorvg/thorvg/wiki/Package-Distrubution

### Updates Announcement
- [x] Release Note

**Comment by hermet** [comment]
https://github.com/thorvg/thorvg/wiki/24'-Development-Roadmap

**Comment by hermet** [comment]
See: https://github.com/thorvg/thorvg/wiki/24'-Development-Roadmap

**Comment by hermet** [comment]
Out of v0.13 release as known Issues:
- [ ] https://github.com/thorvg/thorvg/issues/2072
- [ ] https://github.com/thorvg/thorvg/issues/2078
- [ ] https://github.com/thorvg/thorvg/issues/2013

**Comment by hermet** [comment]
TTF/Lottie Converage is not satisfied:
![image](https://github.com/thorvg/thorvg/assets/3711518/8a9f4d6d-4d10-417e-9a9d-70579e56cc4b)

![image](https://github.com/thorvg/thorvg/assets/3711518/5fce4437-1467-456c-8ce8-02c9dd504f04)
![image](https://github.com/thorvg/thorvg/assets/3711518/3c9ae019-bf53-4c72-8d5f-5a1aa4ce2402)

**Comment by hermet** [comment]
The latest:
![image](https://github.com/thorvg/thorvg/assets/3711518/72545e12-40e2-4a37-82e3-75c851f08791)

**Comment by hermet** [comment]
Ready v0.13.x branch: https://github.com/thorvg/thorvg/tree/v0.13.x

**Comment by hermet** [comment]
@tinyjin v0.13.0 has been tagged. Please update lottie-player, viewer, test-automation.
https://github.com/thorvg/thorvg/releases/tag/v0.13.0

**Comment by tinyjin** [comment]
> @tinyjin v0.13.0 has been tagged. Please update lottie-player, viewer, test-automation. https://github.com/thorvg/thorvg/releases/tag/v0.13.0

ALL DONE!
https://www.npmjs.com/package/@thorvg/lottie-player/v/1.0.0-beta.13
