### ISSUE TITLE
ThorVG v0.14 Release

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2403]
### Tasks Review
- [x] https://github.com/thorvg/thorvg/issues/2468
- [x] https://github.com/thorvg/thorvg/issues/2465
- [x] https://github.com/thorvg/thorvg/issues/2282
- [x] https://github.com/thorvg/thorvg/issues/2401
- [x] https://github.com/thorvg/thorvg/issues/2374
- [x] https://github.com/thorvg/thorvg/issues/2347
- [x] https://github.com/thorvg/thorvg/issues/2146
- [x] https://github.com/thorvg/thorvg/issues/2124
- [x] https://github.com/thorvg/thorvg/issues/1991
- [x] https://github.com/thorvg/thorvg/issues/1244

### API Clean UP
- [x] https://github.com/thorvg/thorvg/pull/2450
- [x] https://github.com/thorvg/thorvg/pull/2458
- [x] https://github.com/thorvg/thorvg/pull/2474

### Unit Test
- [x] Make it up 80% coverage https://github.com/thorvg/thorvg/wiki/Unit-Tests

### Regression Test
- [x] Memory Sanitizer (Examples / Unit-Tests)  //-Db_sanitize="address,undefined"
  - [x] https://github.com/thorvg/thorvg/issues/2461
- [x] Thread Sanitizer (Examples / Unit-Tests)    //-Db_sanitize="thread"
  - [x] https://github.com/thorvg/thorvg/issues/2462
- [x] Unit-Tests
- [x] TVG binary compatibility
- [x] Examples
- [x] Tools (svg2png / svg2tvg / lottie2gif)
- [x] GL Engine capability https://github.com/thorvg/thorvg/issues/1687
- [x] WG Engine capability https://github.com/thorvg/thorvg/issues/1479

### Update the TVG Pictures
- [x] Update the TVG Pictures in [examples, test] with the latest SVG resources
- [x] Back up the new generated tvg picture binaries to https://github.com/thorvg/tvgpack

### Performance Comparison
- [x] Stress Test (at the sampling 1000, within the margin of error)
  - [x] Performance (SW) = **0.93x slower** (EFL: 13ms -> 14ms)    //SDL2: 8ms
  - [x] Lottie (SW) = **1.0x faster** (EFL: 21ms -> 21ms)    //SDL2: 26ms
  - [x] Performance (GL) = 17ms    //SDL2
  - [x] Lottie (GL) = 119ms    //SDL2
- [x] Binary size diff (**Full set:** loaders="all", savers="all", bindings="capi")
  - [x] Base: Sw Raster with the vector drawing primitives = **+4kb** (139kb -> 143kb)
  - [x] Base + SVG loader only = **+8kb** (205kb -> 213kb)
  - [x] Base + Lottie loader with static (lottie, png, jpg, webp), without thread = **+295kb** (344kb -> 639kb)    //by expression engine, +283kb
  - [x] Base + Full set with external = **+295kb** (332kb -> 627kb)    //by expression engine +283kb
  - [x] Base + Full set with static = **+299kb** (455kb -> 754kb)    //by expression engine +283kb
- [x] ThorVG Player
  - [x] FPS = 97 fps
  - [x] Memory = 32 mb
  - [x] [LightHouse](https://pagespeed.web.dev/analysis/https-thorvg-perf-test-vercel-app/xxqk38r5n7?form_factor=desktop&category=performance&category=accessibility&category=best-practices&category=seo&hl=en-US&utm_source=lh-chrome-ext) =  99 / 94 / 100 / 100

### Build Test
- [x] Build errors / warnings (Web/Ubuntu/Windows/MacOS)

### Update API Documentation
- [x] Update the api documenation with doxygen 

### Update the thorvg package
- [x] ThorVG Web https://github.com/thorvg/thorvg.web
- [x] ThorVG Android https://github.com/thorvg/thorvg.android
- [x] ThorVG Player https://www.npmjs.com/package/@thorvg/lottie-player
- [x] ThorVG Viewer https://github.com/thorvg/thorvg.viewer
- [x] ThorVG Test Automation https://github.com/thorvg/thorvg.test-automation
- [ ] MSYS2 https://github.com/thorvg/thorvg/wiki/Package-Distrubution
- [ ] vcpkg https://github.com/thorvg/thorvg/wiki/Package-Distrubution
- [ ] Conan https://github.com/thorvg/thorvg/wiki/Package-Distrubution

### Updates Announcement
- [x] Release Note

**Comment by hermet** [comment]
Reserved milestone v0.15: https://github.com/thorvg/thorvg/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.15

**Comment by hermet** [comment]
branch v0.14.x: https://github.com/thorvg/thorvg/tree/v0.14.x

**Comment by capnm** [comment]
Godot PR ready, see no Linux64 issues: https://github.com/godotengine/godot/pull/93655

**Comment by fire** [comment]
https://github.com/thorvg/thorvg/releases/tag/v0.14.0 is not tagged as release. Is this intended?

**Comment by hermet** [comment]
> t tagged as release. Is this intended?

@fire Yes, it's just on ready. it will be released on this Friday or this Weekend, tops.

**Comment by hermet** [comment]
@fire https://github.com/thorvg/thorvg/releases/tag/v0.14.0 released now.

**Comment by hermet** [comment]
Perf-Test Seed: 
```
seed=ZmxlY2hlLDExNTU1LGJhdG1hbixwZXJzb25hbF9jaGFyYWN0ZXIseWFybl9sb2FkaW5nLDUzNDQtaG9uZXktc2Fjay1odWQsZmllcnlfc2t1bGwsbGlrZV9idXR0b24sZGFuY2luZ19ib29rLHdhbGtlcixyYWRhcixyaXBwbGVfbG9hZGluZ19hbmltYXRpb24sZG9kZWNhaGVkcm9uLGZvb2RyYXRpbmcsc2t1bGxib3ksZ2FtZV9maW5pc2hlZCxwcm9wZXJ0eV9tYXJrZXQsaGFtYnVyZ2VyLGZ1bmt5X2NoaWNrZW4sZGF5X3RvX25pZ2h0LGdyYWRpZW50X2luZmluaXRlLHN0YXJzdHJpcHMsc2t1bGxib3ksYV9tb3VudGFpbixmbHlfaW5fYmVha2VyLHJpcHBsZV9sb2FkaW5nX2FuaW1hdGlvbixsaWtlX2J1dHRvbix0ZXh0LG1lcmdpbmdfc2hhcGVzLG9wZW5fZW52ZWxvcGUsdm9pY2VfcmVjb2duaXRpb24sbGFfY29tbXVuYXV0ZSx2b2ljZV9yZWNvZ25pdGlvbiw1MzE3LWZpcmV3b3JrZHMsb3Blbl9lbnZlbG9wZSxoYXBweV90cmlvLGJpcnRoX3N0b25lX2xvZ28sZm9vZHJhdGluZyxwZXJzb25hbF9jaGFyYWN0ZXIsZ3JhZGllbnRfc2xlZXB5X2xvYWRlcixhbnViaXMsbWVzc2FnZSxmb2NhbF90ZXN0LHdpbmRtaWxsLGxvYWRpbmdfcmVjdGFuZ2xlLGZvY2FsX3Rlc3QsZ3Jvd3VwLHRleHQyLGxvbG9fd2FsayxkdWNr&count=50
```
